
// This file has been generated by the GUI designer. Do not modify.
namespace Heart
{
	public partial class MainWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Entry CommandEnter;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::Gtk.TextView ConsoleView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Heart.MainWindow
			this.Name = "Heart.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Heart.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CommandEnter = new global::Gtk.Entry ();
			this.CommandEnter.WidthRequest = 912;
			this.CommandEnter.CanDefault = true;
			this.CommandEnter.CanFocus = true;
			this.CommandEnter.Name = "CommandEnter";
			this.CommandEnter.IsEditable = true;
			this.fixed1.Add (this.CommandEnter);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CommandEnter]));
			w1.X = 8;
			w1.Y = 453;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.WidthRequest = 920;
			this.scrolledwindow2.HeightRequest = 436;
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.ConsoleView = new global::Gtk.TextView ();
			this.ConsoleView.Name = "ConsoleView";
			this.ConsoleView.Editable = false;
			this.ConsoleView.AcceptsTab = false;
			this.scrolledwindow2.Add (this.ConsoleView);
			this.fixed1.Add (this.scrolledwindow2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.scrolledwindow2]));
			w3.X = 6;
			w3.Y = 5;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 932;
			this.DefaultHeight = 491;
			this.CommandEnter.HasDefault = true;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.CommandEnter.Activated += new global::System.EventHandler (this.Command_Entry_Enter);
			this.ConsoleView.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.ConsoleViewScrollAuto);
		}
	}
}
